- name: hello-world-apb provision
  hosts: localhost
  gather_facts: false
  connection: local
  roles:
  - role: ansible.kubernetes-modules
    install_python_requirements: no
  - role: hello-world-apb
  vars:
    apb_action: provision

# Configure each container with its role
- name: hello-world-apb playbook to configure the hello-world container
  hosts: hello-world-*
  gather_facts: false
  connection: kubectl
    kubectl_container: hello-world
    kubectl_namespace: '{{ namespace }}'
  roles:
  - role: config-hello-world-container
